package helper

const TABLE_TOP_LEFT = '┌'
const TABLE_TOP_RIGHT = '┐'
const TABLE_BOTTOM_LEFT = '└'
const TABLE_BOTTOM_RIGHT = '┘'
const TABLE_HORIZONTAL = '─'
const TABLE_VERTICAL = '│'
const TABLE_INTERSECTION_RIGHT = '┤'
const TABLE_INTERSECTION_LEFT = '├'
const TABLE_INTERSECTION_TOP = '┬'
const TABLE_INTERSECTION_BOTTOM = '┴'
const TABLE_INTERSECTION = '┼'
const EMPTY_SLOT = '◾'
const FILLED_SLOT = '◽'
